#!/usr/bin/env python3
"""
Convert firmware .hex file to Gowin BSRAM .mi init files.

The firmware is stored in 4 BSRAM blocks (bootram_2kx8_0..3) for a 32-bit bus.
Each BSRAM holds one byte of each 32-bit word:
- bootram_0: bytes 0, 4, 8, 12, ...  (bits [7:0])
- bootram_1: bytes 1, 5, 9, 13, ...  (bits [15:8])
- bootram_2: bytes 2, 6, 10, 14, ... (bits [23:16])
- bootram_3: bytes 3, 7, 11, 15, ... (bits [31:24])

Input: fw-brom.hex (Intel HEX format, generated by objcopy)
Output: boot_rom_N.mi files in Gowin .mi format
"""

import sys
import os

def parse_intel_hex(hex_file):
    """Parse Intel HEX file and return byte array"""
    memory = {}
    base_addr = 0

    with open(hex_file, 'r') as f:
        for line in f:
            line = line.strip()
            if not line.startswith(':'):
                continue

            byte_count = int(line[1:3], 16)
            address = int(line[3:7], 16)
            record_type = int(line[7:9], 16)
            data = line[9:9+byte_count*2]

            if record_type == 0x00:  # Data record
                addr = base_addr + address
                for i in range(byte_count):
                    byte_val = int(data[i*2:i*2+2], 16)
                    memory[addr + i] = byte_val
            elif record_type == 0x04:  # Extended linear address
                base_addr = int(data, 16) << 16
            elif record_type == 0x01:  # EOF
                break

    return memory

def memory_to_mi_files(memory, output_dir, base_addr=0x80000000, size=8192):
    """
    Split memory into 4 .mi files for 4-way interleaved BSRAM.
    Size is in bytes (8KB = 2048 32-bit words).
    """

    # Create 4 arrays for the 4 BSRAM blocks (one per byte lane)
    bram = [bytearray(size // 4) for _ in range(4)]

    # Fill BRAM arrays from memory
    for offset in range(size):
        addr = base_addr + offset
        byte_val = memory.get(addr, 0x00)  # Default to 0 if address not in hex

        # Determine which BSRAM and which offset within it
        word_index = offset // 4      # Which 32-bit word
        byte_lane = offset % 4         # Which byte within the word (0-3)

        bram[byte_lane][word_index] = byte_val

    # Write .mi files
    for i in range(4):
        mi_file = os.path.join(output_dir, f'boot_rom_{i}.mi')
        with open(mi_file, 'w') as f:
            # Write header comment
            f.write(f'// Boot ROM byte lane {i} (bits [{i*8+7}:{i*8}])\n')
            f.write(f'// Generated from fw-brom.hex\n')
            f.write(f'#File_format=Hex\n')
            f.write(f'#Address_depth={len(bram[i])}\n')
            f.write(f'#Data_width=8\n')

            # Write data (4 bytes per line for readability)
            for addr in range(0, len(bram[i]), 4):
                line_bytes = bram[i][addr:addr+4]
                hex_str = ' '.join(f'{b:02X}' for b in line_bytes)
                f.write(f'{hex_str}\n')

        print(f'Generated {mi_file}')

def main():
    if len(sys.argv) < 2:
        print('Usage: hex_to_mi.py <fw-brom.hex> [output_dir]')
        sys.exit(1)

    hex_file = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(hex_file)

    if not os.path.exists(hex_file):
        print(f'Error: {hex_file} not found')
        sys.exit(1)

    print(f'Parsing {hex_file}...')
    memory = parse_intel_hex(hex_file)

    print(f'Found {len(memory)} bytes in hex file')
    if memory:
        min_addr = min(memory.keys())
        max_addr = max(memory.keys())
        print(f'Address range: 0x{min_addr:08X} - 0x{max_addr:08X}')

    print(f'Generating .mi files in {output_dir}...')
    memory_to_mi_files(memory, output_dir)

    print('Done!')

if __name__ == '__main__':
    main()
