// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vuart_handshake_test.cpp"
#include "Vuart_handshake_test___024root__DepSet_haa9a6acc__0.cpp"
#include "Vuart_handshake_test___024root__DepSet_hac7155c0__0.cpp"
#include "Vuart_handshake_test__Trace__0.cpp"
#include "Vuart_handshake_test___024root__Slow.cpp"
#include "Vuart_handshake_test___024root__DepSet_haa9a6acc__0__Slow.cpp"
#include "Vuart_handshake_test___024root__DepSet_hac7155c0__0__Slow.cpp"
#include "Vuart_handshake_test__Syms.cpp"
#include "Vuart_handshake_test__Trace__0__Slow.cpp"
#include "Vuart_handshake_test__TraceDecls__0__Slow.cpp"
