apiVersion: v1
kind: ServiceAccount
metadata:
  name: atomik
  namespace: {{ include "atomik.namespace" . }}
  labels:
    {{- include "atomik.labels" . | nindent 4 }}
automountServiceAccountToken: false
