apiVersion: v1
kind: Service
metadata:
  name: atomik-metrics
  namespace: {{ include "atomik.namespace" . }}
  labels:
    {{- include "atomik.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "atomik.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.prometheus.port }}
      targetPort: metrics
      protocol: TCP
